### ISSUE TITLE
cachebust parameter not working?

### ISSUE THREAD

**Issue by bradchoate** [wellington/wellington#202]
I've tried:

    --cachebust="ts"

and used the `image-url()` in my SASS file. I'm getting the correct relative path to the image in the CSS, but no cachebust parameter. I've tried both the homebrew install and the Docker image. What am I doing wrong?
#

**Comment by drewwells** [comment]
can you include your code?

**Comment by bradchoate** [comment]
In static/sass/test.scss:

```scss
.thing {
    background-image: image-url("static/images/test.png");
}
```

Execution:

    wt compile --cachebust="ts" --build="static/css" static/sass/test.scss

Result in static/css/test.css:

```css
.test {
  background-image: url('../../static/images/test.png'); }
```

Versions:

```
$ wt --version
   libsass: 3.3.6
Wellington: 1.0.4
```
